/* ADMIN */
export const SET_ADMIN_MENU_ACTIVE = 'SET_ADMIN_MENU_ACTIVE';

export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER_FROM_LIST = 'REMOVE_USER_FROM_LIST';

export const LOAD_PRODUCT_LIST = 'LOAD_PRODUCT_LIST';
export const REMOVE_PRODUCT_FROM_LIST = 'REMOVE_PRODUCT_FROM_LIST';

export const LOAD_CATEGORY_LIST = 'LOAD_CATEGORY_LIST';
export const REMOVE_CATEGORY_FROM_LIST = 'REMOVE_CATEGORY_FROM_LIST';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';

/* FRONTEND */
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const SET_ACTIVE_PRODUCT_IMAGE = 'SET_ACTIVE_PRODUCT_IMAGE';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';

export const UPDATE_LOGIN_USER = 'UPDATE_LOGIN_USER';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const LOAD_ORDER_LIST = 'LOAD_ORDER_LIST';
export const LOAD_ORDER = 'LOAD_ORDER';